export const detailGridData = [
  {
    title: "Total Address",
    value: "7",
    showAddress: true,
    showAddressText: "View Address",
  },
  { title: "Total amount to send", value: "25.001" },
  { title: "No. of transaction", value: "7" },
  { title: "Your token balance", value: "888888.88" },
  { title: "Token to send", value: "T1" },
  { title: "Liquidity", value: "3 BNB" },
];
export const detailGridData2 = [
  { title: "Total Token ", value: "850,520,000 STK" },
  { title: "Token name", value: "Saul token" },
  { title: "Token symbol", value: "3 BNB" },
  { title: "Token decimals", value: "3 BNB" },
  { title: "Sale method", value: "0 BNB" },
  { title: "Liquidity", value: "3 BNB" },
  { title: "Liquidity lockup time", value: "3 BNB" },
  { title: "Listing Rate", value: "950000 STK" },
  { title: "First token release after listing ($days)", value: "10 BNB" },
  { title: "Maximum Buy", value: "10 BNB" },
  { title: "Minimum Buy", value: "30 BNB" },
  { title: "Softcap", value: "100 BNB" },
  { title: "Hardcap", value: "300 BNB" },
  { title: "Start Time", value: "03:46 (UTC)" },
  { title: "End Time", value: "03:46 (UTC)" },
  { title: "Presale rate", value: "1000000 STK" },
  { title: "Website", value: "saultoken.com" },
  { title: "Twitter", value: "@saultoken" },
  { title: "This is the first token to reward with", value: "Discription" },
];
