/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IPoolManagerInterface extends utils.Interface {
  functions: {
    "addPoolFactory(address)": FunctionFragment;
    "addTopPool(address,uint256)": FunctionFragment;
    "decreaseTotalValueLocked(uint256)": FunctionFragment;
    "increaseTotalValueLocked(uint256)": FunctionFragment;
    "isPoolGenerated(address)": FunctionFragment;
    "poolForToken(address)": FunctionFragment;
    "privatePoolForToken(string)": FunctionFragment;
    "recordContribution(address,address)": FunctionFragment;
    "registerPool(address,address,address,uint8)": FunctionFragment;
    "registerPrivatePool(address,string,address,uint8)": FunctionFragment;
    "removePoolForToken(address,address)": FunctionFragment;
    "removePrivatePoolForToken(string,address)": FunctionFragment;
    "removeTopPool(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addPoolFactory"
      | "addTopPool"
      | "decreaseTotalValueLocked"
      | "increaseTotalValueLocked"
      | "isPoolGenerated"
      | "poolForToken"
      | "privatePoolForToken"
      | "recordContribution"
      | "registerPool"
      | "registerPrivatePool"
      | "removePoolForToken"
      | "removePrivatePoolForToken"
      | "removeTopPool"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addPoolFactory",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addTopPool",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseTotalValueLocked",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseTotalValueLocked",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isPoolGenerated",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "poolForToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "privatePoolForToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "recordContribution",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPool",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPrivatePool",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removePoolForToken",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removePrivatePoolForToken",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTopPool",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addPoolFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addTopPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseTotalValueLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseTotalValueLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPoolGenerated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "privatePoolForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPrivatePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePoolForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePrivatePoolForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTopPool",
    data: BytesLike
  ): Result;

  events: {
    "ContributionUpdated(uint256)": EventFragment;
    "PoolForTokenRemoved(address,address)": EventFragment;
    "PrivatePoolForTokenRemoved(string,address)": EventFragment;
    "TvlChanged(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContributionUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolForTokenRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PrivatePoolForTokenRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TvlChanged"): EventFragment;
}

export interface ContributionUpdatedEventObject {
  totalParticipations: BigNumber;
}
export type ContributionUpdatedEvent = TypedEvent<
  [BigNumber],
  ContributionUpdatedEventObject
>;

export type ContributionUpdatedEventFilter =
  TypedEventFilter<ContributionUpdatedEvent>;

export interface PoolForTokenRemovedEventObject {
  token: string;
  pool: string;
}
export type PoolForTokenRemovedEvent = TypedEvent<
  [string, string],
  PoolForTokenRemovedEventObject
>;

export type PoolForTokenRemovedEventFilter =
  TypedEventFilter<PoolForTokenRemovedEvent>;

export interface PrivatePoolForTokenRemovedEventObject {
  tokenName: string;
  pool: string;
}
export type PrivatePoolForTokenRemovedEvent = TypedEvent<
  [string, string],
  PrivatePoolForTokenRemovedEventObject
>;

export type PrivatePoolForTokenRemovedEventFilter =
  TypedEventFilter<PrivatePoolForTokenRemovedEvent>;

export interface TvlChangedEventObject {
  totalLocked: BigNumber;
  totalRaised: BigNumber;
}
export type TvlChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  TvlChangedEventObject
>;

export type TvlChangedEventFilter = TypedEventFilter<TvlChangedEvent>;

export interface IPoolManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPoolManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addPoolFactory(
      factory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addTopPool(
      poolAddress: PromiseOrValue<string>,
      raisedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    decreaseTotalValueLocked(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    increaseTotalValueLocked(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isPoolGenerated(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    poolForToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    privatePoolForToken(
      tokenName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    recordContribution(
      user: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerPool(
      pool: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      version: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerPrivatePool(
      pool: PromiseOrValue<string>,
      tokenName: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      version: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removePoolForToken(
      token: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removePrivatePoolForToken(
      tokenName: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeTopPool(
      poolAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addPoolFactory(
    factory: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addTopPool(
    poolAddress: PromiseOrValue<string>,
    raisedAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  decreaseTotalValueLocked(
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  increaseTotalValueLocked(
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isPoolGenerated(
    pool: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  poolForToken(
    token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  privatePoolForToken(
    tokenName: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  recordContribution(
    user: PromiseOrValue<string>,
    pool: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerPool(
    pool: PromiseOrValue<string>,
    token: PromiseOrValue<string>,
    owner: PromiseOrValue<string>,
    version: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerPrivatePool(
    pool: PromiseOrValue<string>,
    tokenName: PromiseOrValue<string>,
    owner: PromiseOrValue<string>,
    version: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removePoolForToken(
    token: PromiseOrValue<string>,
    pool: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removePrivatePoolForToken(
    tokenName: PromiseOrValue<string>,
    pool: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeTopPool(
    poolAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addPoolFactory(
      factory: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addTopPool(
      poolAddress: PromiseOrValue<string>,
      raisedAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    decreaseTotalValueLocked(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    increaseTotalValueLocked(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    isPoolGenerated(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    poolForToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    privatePoolForToken(
      tokenName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    recordContribution(
      user: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerPool(
      pool: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      version: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerPrivatePool(
      pool: PromiseOrValue<string>,
      tokenName: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      version: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    removePoolForToken(
      token: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removePrivatePoolForToken(
      tokenName: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeTopPool(
      poolAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ContributionUpdated(uint256)"(
      totalParticipations?: null
    ): ContributionUpdatedEventFilter;
    ContributionUpdated(
      totalParticipations?: null
    ): ContributionUpdatedEventFilter;

    "PoolForTokenRemoved(address,address)"(
      token?: PromiseOrValue<string> | null,
      pool?: null
    ): PoolForTokenRemovedEventFilter;
    PoolForTokenRemoved(
      token?: PromiseOrValue<string> | null,
      pool?: null
    ): PoolForTokenRemovedEventFilter;

    "PrivatePoolForTokenRemoved(string,address)"(
      tokenName?: PromiseOrValue<string> | null,
      pool?: null
    ): PrivatePoolForTokenRemovedEventFilter;
    PrivatePoolForTokenRemoved(
      tokenName?: PromiseOrValue<string> | null,
      pool?: null
    ): PrivatePoolForTokenRemovedEventFilter;

    "TvlChanged(uint256,uint256)"(
      totalLocked?: null,
      totalRaised?: null
    ): TvlChangedEventFilter;
    TvlChanged(totalLocked?: null, totalRaised?: null): TvlChangedEventFilter;
  };

  estimateGas: {
    addPoolFactory(
      factory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addTopPool(
      poolAddress: PromiseOrValue<string>,
      raisedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    decreaseTotalValueLocked(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    increaseTotalValueLocked(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isPoolGenerated(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolForToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    privatePoolForToken(
      tokenName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recordContribution(
      user: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerPool(
      pool: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      version: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerPrivatePool(
      pool: PromiseOrValue<string>,
      tokenName: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      version: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removePoolForToken(
      token: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removePrivatePoolForToken(
      tokenName: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeTopPool(
      poolAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addPoolFactory(
      factory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addTopPool(
      poolAddress: PromiseOrValue<string>,
      raisedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    decreaseTotalValueLocked(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    increaseTotalValueLocked(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isPoolGenerated(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolForToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    privatePoolForToken(
      tokenName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recordContribution(
      user: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerPool(
      pool: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      version: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerPrivatePool(
      pool: PromiseOrValue<string>,
      tokenName: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      version: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removePoolForToken(
      token: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removePrivatePoolForToken(
      tokenName: PromiseOrValue<string>,
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeTopPool(
      poolAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
